### ISSUE TITLE
1.0.2.Final Release - error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by vishwajeetdusane** [wildfly/wildfly-openssl#20]
Getting error with 1.0.2.Final version when HTTPS request is initiated

> error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed 

However no issues when 1.0.0.CR5 is used.

**Comment by vishwajeetdusane** [comment]
@stuartwdouglas - Is there a prerequisite expected to consume new version ?

**Comment by stuartwdouglas** [comment]
Do you have a reproducer for this? Some of these fixes were to tighten up certificate verification, but it should still work if your trust store is set up correctly.

**Comment by vishwajeetdusane** [comment]
@stuartwdouglas  - this is always reproducible. 

I am not providing keystore, with assumption that default java keystore will be loaded in the below case, m i wrong ?

`    org.wildfly.openssl.OpenSSLProvider.register();
     SSLContext sslContext =  SSLContext.getInstance("openssl.TLS");
     sslContext.init(null,null,null);
`
My understanding is If the public certificate is not present in the keystore, during SSL handshake - public certification would be accepted and handshake would continue.  Please correct my understanding.

**Comment by vishwajeetdusane** [comment]
@stuartwdouglas  - I passed down TrustManager as 

`       Code change
      
      sslContext.init(null, new TrustManager[] { new X509TrustManager() {

      @Override
      public void checkClientTrusted(X509Certificate[] cert, String authType) {
      }

      @Override
      public void checkServerTrusted(X509Certificate[] cert, String authType) {
      }

      @Override
      public X509Certificate[] getAcceptedIssuers() {
        return null;
      }
    } }, null);
`
Then i do not see any issue. But seems to be unacceptable solution?

**Comment by stuartwdouglas** [comment]
Can you test with the latetst upstream? I have added code to use the default trust manager

**Comment by vishwajeetdusane** [comment]
@stuartwdouglas  - i do not have native build environment to build native code. Will need some time to set this up on Windows. If you have prebuild jar then it would be much quicker for me to verify.

**Comment by stuartwdouglas** [comment]
Unfortunately I am travelling at the moment, so I do not have access to my windows box.

**Comment by vishwajeetdusane** [comment]
@stuartwdouglas  - Alright, i got the setup. I was able to verify with 1.0.3-Final-Snapshot and no need to workaround on trustmanger anymore. Thanks for fixing it 👍
