### ISSUE TITLE
Optimization : Payload > 16KB, gets broken into 16KB + 1KB packets over TCP

### ISSUE THREAD

**Issue by vishwajeetdusane** [wildfly/wildfly-openssl#22]
I did a benchmark for payload 4MB over SSL and observed over wireshark. Payload is broken into 16KB + 1KB.

Benchmark Result - With/Without the optimization

Change | Iteration | Size | 50th |  Avg |  75th | 90th | 95th | 99th | Max | Min 
------------ | ------------ | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- 
17KB Buffer | 10000 | 4MB | 59.0 ms | 69.71 ms | 64.75 ms | 68.0 ms | 70.0 ms | 85.5 ms | 2582.0 ms | 45.0 ms
16KB Buffer | 10000 | 4MB | 41.0 ms | 60.01 ms | 45.0 ms | 49.0 ms | 51.0 ms | 55.2 ms | 4738.0 ms | 34.0 ms

Cipher suite used is TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, Orthogonal to this change.

Reduced DIRECT_POOL for write to 16KB.

**Comment by vishwajeetdusane** [comment]
@stuartwdouglas  - I am not able to push the CR in different branch for review due to permission. Could you please suggest?

**Comment by stuartwdouglas** [comment]
You need to create your own fork and open a pull request from there

**Comment by vishwajeetdusane** [comment]
@stuartwdouglas  - Thanks a lot. Created a pull request.

**Comment by vishwajeetdusane** [comment]
@stuartwdouglas  - Thanks a lot for the review.

**Comment by vishwajeetdusane** [comment]
@stuartwdouglas  - When are you planning to release #22 and #20 ?

**Comment by vishwajeetdusane** [comment]
Hi @stuartwdouglas  - Could you please update of the release with #22 and #20 fixes?

**Comment by stuartwdouglas** [comment]
I will try and do one in the near future, the solaris box I usually use to do the release has broken so I need to source another one, which is the main thing holding me up at the moment.

**Comment by vishwajeetdusane** [comment]
Thanks for the update.
