### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no wfssl in java.library.path

### ISSUE THREAD

**Issue by kyle2008** [wildfly/wildfly-openssl#30]
the error stack:

> Caused by: java.lang.UnsatisfiedLinkError: no wfssl in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.wildfly.openssl.SSL$LibraryLoader.load(SSL.java:288)
        ... 33 common frames omitted

 what should I config my project on linux os? 
thanks very much.

**Comment by jaikiran** [comment]
@vankwang the readme has details on how to set it up here https://github.com/wildfly/wildfly-openssl/blob/master/README.md#installing-the-native-library

**Comment by kyle2008** [comment]
@jaikiran  I am sorry that I reply this topic so late, with your help finally I got success, 
on linux , just do 
``` java
    org.wildfly.openssl.OpenSSLProvider.register()
```
on windows,
   first download the ssl installer, http://slproweb.com/download/Win64OpenSSL-1_1_0h.exe ,
   install it, and then input this code in project,
``` java
    System.setProperty("org.wildfly.openssl.path", "C:\\OpenSSL-Win64\\bin");
    org.wildfly.openssl.OpenSSLProvider.register()
```
it is really much faster than jdk ssl :)
