### ISSUE TITLE
There is a miss in OpenSSLSocket

### ISSUE THREAD

**Issue by wuhongzhi** [wildfly/wildfly-openssl#31]
the code in OpenSSLSocket
=================================
    public int read() throws IOException {
        byte[] b = new byte[1];
        read(b);
        return b[0] & 0xFF;
    }
==================================
it should be accoding to api of java
    public int read() throws IOException {
        byte[] b = new byte[1];
        int r = read(b);
        if (r == -1) return r;
        return b[0] & 0xFF;
    }

**Comment by jaikiran** [comment]
@wuhongzhi, that indeed looks like a bug. Would you like to submit a patch as a pull request?

**Comment by stuartwdouglas** [comment]
Fixed, thanks
