### ISSUE TITLE
double free crash for client mode in high concurrency mode

### ISSUE THREAD

**Issue by machunhui** [wildfly/wildfly-openssl#36]
Hi, 
Last year we met a crash when running in client mode under high concurrnecy scenario, reported a double free error.  It's been a long time so I can't remember the very details, but I'll try to describe it as clear as I can:

Suppose there is a session created in thread A, and A is using the session,  and the session is stored in clientSessionContext,  and then another thread B is creating a client mode sslEngine,  then thread B may be assigned the session(by tryAttachClientsideSession),  then do tls_process_client_hello, then it found the session is not valid, so thread B will create a new session and free this stored session,  At the same time, thread C may creating another clientmode engine, and thread C may trying to call removeCacheEntry(xxx, true)  and will free the session too. 
This will cause a double free.

Besides, there is a potenial memory leak if store many session in sessions without removing them.

**Comment by jaikiran** [comment]
@machunhui, thank you for reporting this. Based on your description, I was able to reproduce the JVM crash due to the race in invalidating the sessions. I have submitted a PR with a potential fix https://github.com/wildfly/wildfly-openssl/pull/38.

>> Besides, there is a potenial memory leak if store many session in sessions without removing them.

I haven't been able to reproduce the memory leak yet. I'll probably have to look through the code a bit more if this is actually possible. Did you actually see this happening? If so, could you explain a bit more on how you reproduced it?

**Comment by machunhui** [comment]
@jaikiran great!
I used to had a similiar patch, by using some synchronized condition to make sure it will can deleted once. But considering of our scenario, we don't need to store a client session to accelerate the speed of getting a session, and considering of the memory leak,  so I just removed the store of the client session.

Yes, I did see the memory leak.  In fact, from the code itself, you'll find there is only an interface of removing from sessions, and not called anywhere, so if an session is put in sessions, it may updated, but it will never get removed from the sessions(we can't rely on customer to call the interface, they don't know session was stored).  so, if there are too many "key“ in the sessions, the sessions will looks like a memory leak。

**Comment by jaikiran** [comment]
So the `sessions` that are maintained in the `OpenSSLSessionContext` get removed as and when the sessions are invalidated (through callbacks). Assuming the invalidation itself doesn't happen for whatever reason, these are further cleared when the cache maintained in the `OpenSSLClientSessionContext` either reaches the max size (defaulting to 100) or when it reaches the session timeout. So even if the invaliadtion doesn't happen, the `sessions` cache does keep getting cleaned as and when needed. If you are indeed seeing this reach beyond the expected size, then please let us know and we'll take a look.

P.S: The PR has been merged so you can try your tests against the latest upstream master branch.

**Comment by machunhui** [comment]
@jaikiran oh, maybe your commit can fix the memory leak issue.
when removeCacheEntry,  the session will be removed from sessions， which was not removed from sessions before.

**Comment by jaikiran** [comment]
>> when removeCacheEntry, the session will be removed from sessions， which was not removed from sessions before.

That's correct. The commit that got merged a few days back made sure the removeCacheEntry does indeed end up removing the session from the `sessions` cache as well.
